# Generated by Django 3.1.7 on 2021-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('sub_catogery', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('color', models.IntegerField(null=True)),
            ],
        ),
    ]
