# Generated by Django 3.1.7 on 2021-05-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='preoduct_id',
            new_name='product_id',
        ),
    ]
